##' A class that defines the gene to geneset mapping.
##'
##' @exportClass GeneSetDb
##'
##' @slot table The "gene set table": a data.table with geneset information,
##'   one row per gene set. Columns include collection, name, N, and n. The end
##'   user can add more columns to this data.table as desired. The actual
##'   feature IDs are computed on the fly by doing a db[J(group, id)]
##' @slot db A \code{data.table} to hold all of the original geneset id
##'   information that was used to construct this \code{GeneSetDb}.
##' @slot featureIdMap Maps the ids used in the geneset lists to the ids
##'   (rows) over the expression data the GSEA is run on
##' @slot collectionMetadata A \code{data.table} to keep metadata about each
##'   individual geneset collection, ie. the user might want to keep track of
##'   where the geneset definitions come from. Perhaps a function that parses
##'   the collection,name combination to generate an URL that points the user
##'   to more information about that geneset, etc.
##' @rdname GeneSetDb-class
.GeneSetDb <- setClass("GeneSetDb",
  slots=c(
    table="data.table",
    db="data.table",
    featureIdMap="data.table",
    collectionMetadata="data.table"),
  prototype=prototype(
    table=data.table(
      collection=character(),
      name=character(),
      active=logical(),
      N=integer(),
      n=integer(),
      key=c('collection', 'name')),
    db=data.table(
      collection=character(),
      name=character(),
      featureId=character(),
      key=c('collection', 'name', 'featureId')),
    featureIdMap=data.table(
      featureId=character(),  ## The ids used in the defined genesets
      x.id=character(),
      x.idx=integer(),
      key='featureId'),
    collectionMetadata=data.table(
      collection=character(),
      name=character(),
      value=list(),
      key=c('collection', 'name'))))

.MultiGSEARegistry <- setClass("MultiGSEARegistry",
  slots=c(
    methods="character",
    validate.fn="list",
    do.fn="list"),
  prototype=prototype(
    methods=character(),
    validate.fn=list(),
    do.fn=list()))

##' A MultiGSEAResult object holds the results from a multiGSEA call.
##'
##' @description A call to \code{\link{multiGSEA}} will produce analyses for an
##' arbitrary number of GSEA methods, the results of which will be stored and
##' accessible here using the \code{\link{result}}, \code{\link{results}}, and
##' \code{\link{resultNames}}.
##'
##' In addition, the \code{\link{GeneSetDb}} used for the analysis is accessible
##' via \code{\link{geneSetDb}}, and the results from the differential
##' expression analysis is available via \code{\link{logFC}}.
##'
##' Visualizing results of a geneset based analysis also are functions that
##' operate over a \code{MultiGSEAResult} object, for instance see the
##' \code{\link{iplot}} and \code{\link{explore}} functions.
##'
##' @exportClass MultiGSEAResult
##' @rdname MultiGSEAResult
##' @aliases MultiGSEAResult
##'
##' @slot gsd The \linkS4class{GeneSetDb} this analysis was run over
##' @slot results The list of individual results generated by each of the
##'   GSEA methods that were run.
##' @slot logFC The differential expression statistics for each individual
##'   feature measured in the experiment.
.MultiGSEAResult <- setClass("MultiGSEAResult",
  slots=c(
    gsd="GeneSetDb",
    results="list",
    logFC='data.table'),
  prototype=prototype(
    gsd=new("GeneSetDb"),
    results=list(),
    # logFC=data.table(
    #   featureId=character(),
    #   logFC=numeric(),
    #   t=numeric(),
    #   pval=numeric(),
    #   padj=numeric(),
    #   key='featureId')))
    logFC=data.table(
      featureId=character(),
      logFC=numeric(),
      t=numeric(),
      pval=numeric(),
      padj=numeric())))
