## This module enables *complete browsing* of the behavior of the genesets in
## a MultiGSEAResultContainer.
##
## Internally it consists of a geneSetSelect module, too.
##
## Note that this module is not concerned with the statistics generated by
## a particular GSEA method, but rather the differential logFC or t-stats for
## the genes in a geneset

##' A module to encapsulate browsing differential statistics of a geneset.
##'
##' The module is meant to be displayed in "a box". A geneset picker is at the
##' top of the box. The main content consists of a a
##' \code{\link[miniUI]{miniTabStripPanel}}, which provides a vizual view as
##' well as a tabular view of the statistics for a particular geneset from a
##' \code{MultiGSEAResultContainer}
##'
##' @importFrom miniUI miniTabstripPanel miniTabPanel miniContentPanel
##' @importFrom shiny NS tagList tags fluidRow column selectInput downloadButton
##' @importFrom shiny icon downloadHandler
##' @importFrom DT dataTableOutput
##' @export
##'
##' @param id the shiny id of the module
##' @param mg the \code{MultiGSEAResultContainer}
##' @param server are the tabular bits rendered on teh server side
##' @param height the height of the module
##' @return a tagList of html stuff to dump into the UI
##' @rdname geneSetContrastViewModule
geneSetContrastViewUI <- function(id, height="590px", width="400px") {
  ns <- NS(id)

  tagList(
    tags$div(
      # class="gadget-container", style=paste("height:", height),
      class="gadget-container",
      style=sprintf("height: %s; width %s;", height, width),
      tags$div(
        style="padding: 0 5px 0 5px",
        geneSetSelectUI(ns("gs_select"), "Select Gene Set")),
      miniTabstripPanel(
        miniTabPanel(
          "Visualize", icon = icon("area-chart"),
          miniContentPanel(
            rbokehOutput(ns("gs_viz"), height="350px"),
            fluidRow(
              column(
                8,
                selectInput(ns("gs_viz_type"), NULL,
                            c('boxplot', 'density'), 'boxplot')),
              column(
                4,
                selectInput(ns("gs_viz_stat"), NULL,
                            c('logFC'='logFC', 't-statistic'='t'), 'logFC'))
            )
          )
        ), ## Viz miniTabPanel
        miniTabPanel(
          "Genes", icon = icon("table"),
          miniContentPanel(
            DT::dataTableOutput(ns("gs_members")),
            downloadButton(ns("gs_gene_table"), 'Download'))
        ) ## Members Table miniTabPanel
      ) ## miniTabstripPanel
    ) ## div.gadget-container
  ) ## tagList
}

##' @export
##' @importFrom shiny callModule reactive req downloadHandler outputOptions
##' @importFrom DT renderDataTable
##' @rdname geneSetContrastViewModule
geneSetContrastView <- function(input, output, session, mgc,
                                server=TRUE, maxOptions=Inf, sep="_::_") {
  gs <- callModule(geneSetSelect, 'gs_select', mgc, server=server,
                   maxOptions=maxOptions, sep=sep)
  plt <- reactive({
    req(gs())
    ns <- session$ns
    iplot(mgc()$mg, gs()$collection, gs()$name,
          value=input$gs_viz_stat,
          type=input$gs_viz_type,
          main=NULL, with.legend=FALSE, with.data=TRUE) %>%
      tool_box_select(callback=shiny_callback(ns('selected')), 'points')
  })

  selected_features <- reactive({
    brushed <- input$selected
    if (!is.null(brushed)) {
      brushed <- plt()$data$featureId[brushed + 1L]
    } else {
      brushed <- character()
    }
    brushed
  })

  output$gs_viz <- renderRbokeh({
    req(plt())
  })
  # outputOptions(output, "gs_viz", suspendWhenHidden=FALSE)

  output$gs_members <- DT::renderDataTable({
    req(gs())
    renderGeneSetStatsDataTable(gs()$stats, gs()$name, digits=3)
  }, server=server)

  output$gs_gene_table <- downloadHandler(
    filename=function() {
      sprintf('multiGSEA-gene-statistics-%s_%s.csv', gs()$collection, gs()$name)
    },
    content=function(file) {
      write.csv(gs()$stats, file, row.names=FALSE)
    }
  )

  outputOptions(output, "gs_gene_table", suspendWhenHidden=FALSE)


  vals <- reactive({
    list(gs=gs, selected=selected_features)
  })

  return(vals)
}

##' @export
##' @rdname geneSetContrastViewModule
updateGeneSetContrastViewGeneSet <- function(session, id, label=NULL,
                                             choices=NULL, selected=NULL,
                                             options=list(), server=FALSE) {
  ns <- session$makeScope(id)$ns
  updateGeneSetSelect(session, ns('gs_select'), label=label, choices=choices,
                      selected=selected, options=options, server=server)
}
